services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - meters_app_postgres_data:/var/lib/postgresql
    networks:
      - backend

  rabbitmq:
    image: masstransit/rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - meters_app_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  weakappapi:
    image: regen31/weakapp:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  dataingestor:
    image: ghcr.io/dendubina-org/meters-app-data-ingestor:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8081
      RabbitMqOptions__Host: ${RABBITMQ_HOST}
      RabbitMqOptions__UserName: ${RABBITMQ_USER}
      RabbitMqOptions__Password: ${RABBITMQ_PASSWORD}
      WeakAppOptions__BaseUrl: ${WEAKAPP_BASE_URL}
      WeakAppOptions__ApiKey: ${WEAKAPP_API_KEY}
      WeakAppOptions__RequestIntervalSec: ${WEAKAPP_REQUEST_INTERVAL}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  dataprocessor:
    image: ghcr.io/dendubina-org/meters-app-data-processor:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8083
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      RabbitMqOptions__Host: ${RABBITMQ_HOST}
      RabbitMqOptions__UserName: ${RABBITMQ_USER}
      RabbitMqOptions__Password: ${RABBITMQ_PASSWORD}
      DbMigrationsOptions__RunOnStartup: ${MIGRATE_DB_ON_STARTUP}
      DbMigrationsOptions__MaxRetries: ${MIGRATION_MAX_RETRIES}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  graphqlgateway:
    image: ghcr.io/dendubina-org/meters-app-graph-ql-gateway:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8084
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      CorsOptions__AllowedOrigins__0: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

  notifications:
    image: ghcr.io/dendubina-org/meters-app-notifications:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8085
      RabbitMqOptions__Host: ${RABBITMQ_HOST}
      RabbitMqOptions__UserName: ${RABBITMQ_USER}
      RabbitMqOptions__Password: ${RABBITMQ_PASSWORD}
      CorsOptions__AllowedOrigins__0: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend
      - frontend

  frontend:
    image: ghcr.io/dendubina-org/meters-app-frontend:latest
    restart: unless-stopped
    networks:
      - frontend
    ports:
    - "3000:80"

networks:
  backend:
    internal: true
  frontend:
    internal: false

volumes:
  meters_app_postgres_data:
  meters_app_rabbitmq_data:
