services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - meters_app_postgres_data:/var/lib/postgresql
    networks:
      - backend

  rabbitmq:
    image: masstransit/rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - meters_app_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  weakapp-api:
    image: regen31/weakapp:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  data-ingestor:
    build:
      context: ./Backend
      dockerfile: Services/DataIngestorService/DataIngestor.Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8081
      RabbitMqOptions__Host: ${RABBITMQ_HOST}
      RabbitMqOptions__UserName: ${RABBITMQ_USER}
      RabbitMqOptions__Password: ${RABBITMQ_PASSWORD}
      WeakAppOptions__BaseUrl: ${WEAKAPP_BASE_URL}
      WeakAppOptions__ApiKey: ${WEAKAPP_API_KEY}
      WeakAppOptions__RequestIntervalSec: ${WEAKAPP_REQUEST_INTERVAL}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  data-cleaner:
    build:
      context: ./Backend
      dockerfile: Services/DataCleanerService/DataCleaner.Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8082
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend

  data-processor:
    build:
      context: ./Backend
      dockerfile: Services/DataProcessorService/DataProcessor.Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8083
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      RabbitMqOptions__Host: ${RABBITMQ_HOST}
      RabbitMqOptions__UserName: ${RABBITMQ_USER}
      RabbitMqOptions__Password: ${RABBITMQ_PASSWORD}
      DbMigrationsOptions__RunOnStartup: ${MIGRATE_DB_ON_STARTUP}
      DbMigrationsOptions__MaxRetries: ${MIGRATION_MAX_RETRIES}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  graphql-gateway:
    build:
      context: ./Backend
      dockerfile: Services/GraphQLGatewayService/GraphQLGateway.Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8084
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      CorsOptions__AllowedOrigins__0: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    ports:
      - "8084:8084"

  notifications:
    build:
      context: ./Backend
      dockerfile: Services/NotificationsService/Notifications.Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8085
      RabbitMqOptions__Host: ${RABBITMQ_HOST}
      RabbitMqOptions__UserName: ${RABBITMQ_USER}
      RabbitMqOptions__Password: ${RABBITMQ_PASSWORD}
      CorsOptions__AllowedOrigins__0: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend
      - frontend
    ports:
      - "8085:8085"

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_SENSORS_HUB_URL: ${VITE_SENSORS_HUB_URL}
    restart: unless-stopped
    networks:
      - frontend
    ports:
    - "3000:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - backend
      - frontend
    depends_on:
      - data-ingestor
      - data-cleaner
      - data-processor
      - graphql-gateway
      - notifications

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "5000:3000"
    networks:
      - backend
      - frontend
    volumes:
      - meters_app_grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  backend:
    internal: true
  frontend:
    internal: false

volumes:
  meters_app_postgres_data:
  meters_app_rabbitmq_data:
  meters_app_grafana-data:
