global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "meters-app"
    metrics_path: /metrics
    static_configs:
      - targets:
          - data-ingestor:8081
          - data-processor:8083
          - graphql-server:8084
          - notifications:8085
