name: Build & Push Docker Images

on:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Backend services ----------

      - name: Build & push DataIngestor
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./Backend
          file: ./Backend/Services/DataIngestorService/DataIngestor.Api/Dockerfile
          push: false
          # tags: |
          #   metersacr.azurecr.io/dataingestor:latest
          #   metersacr.azurecr.io/dataingestor:${{ github.sha }}

      - name: Build & push DataProcessor
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./Backend
          file: ./Backend/Services/DataProcessorService/DataProcessor.Api/Dockerfile
          push: false
          # tags: |
          #   metersacr.azurecr.io/dataprocessor:latest
          #   metersacr.azurecr.io/dataprocessor:${{ github.sha }}

      - name: Build & push GraphQL Gateway
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./Backend
          file: ./Backend/Services/GraphQLGatewayService/GraphQLGateway.Api/Dockerfile
          push: false
          # tags: |
          #   metersacr.azurecr.io/graphqlgateway:latest
          #   metersacr.azurecr.io/graphqlgateway:${{ github.sha }}

      - name: Build & push Notifications
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./Backend
          file: ./Backend/Services/NotificationsService/Notifications.Api/Dockerfile
          push: false
          # tags: |
          #   metersacr.azurecr.io/notifications:latest
          #   metersacr.azurecr.io/notifications:${{ github.sha }}

      # ---------- Frontend ----------
      - name: Build & push Frontend
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./Frontend
          push: false
          build-args: |
            VITE_API_BASE_URL=https://api.example.com
            VITE_SENSORS_HUB_URL=https://hub.example.com
          # tags: |
          #   metersacr.azurecr.io/frontend:latest
          #   metersacr.azurecr.io/frontend:${{ github.sha }}
